<%@ Page Title="" Language="C#" MasterPageFile="~/teht3.master" AutoEventWireup="true" CodeFile="g2456_teht7.aspx.cs" Inherits="g2456_teht7" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:LoginStatus ID="LoginStatus1" runat="server" 
        OnLoggingOut="LoginStatus1_LoggingOut" />
    <asp:GridView ID="autoNakyma" runat="server" 
        AllowSorting="True" 
        AllowPaging="True" 

        AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" 

        OnSorting="autoNakyma_Sorting" 
        OnPageIndexChanging="autoNakyma_PageIndexChanging" 
        OnRowCancelingEdit="autoNakyma_RowCancelingEdit" 
        OnRowDeleting="autoNakyma_RowDeleting" 
        OnRowEditing="autoNakyma_RowEditing" 
        OnRowUpdating="autoNakyma_RowUpdating" >

    </asp:GridView>
    <asp:Button ID="addNew" runat="server" OnClick="addNew_Click" Text="Lisää uusi" />
    <asp:Button ID="btnSave" runat="server" OnClick="btnSave_Click" Text="Tallenna" />
    <br />
    <asp:Login ID="LoginWindow" runat="server" 
        OnAuthenticate="LoginWindow_Authenticate" 
        OnLoggingIn="LoginWindow_LoggingIn" 
        OnLoginError="LoginWindow_LoginError" 
        RememberMeText="Remember me." OnLoggedIn="LoginWindow_LoggedIn">
    </asp:Login>
    <asp:Label ID="lblInfo" runat="server"></asp:Label>
</asp:Content>

