<%@ Page Title="" Language="C#" MasterPageFile="~/teht3.master" AutoEventWireup="true" CodeFile="g2456_teht7.aspx.cs" Inherits="g2456_teht7" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="autoNakyma" runat="server" 
        AllowSorting="True" 
        AllowPaging="True" 

        AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" 

        OnSorting="autoNakyma_Sorting" 
        OnPageIndexChanging="autoNakyma_PageIndexChanging" 
        OnRowCancelingEdit="autoNakyma_RowCancelingEdit" 
        OnRowDeleting="autoNakyma_RowDeleting" 
        OnRowEditing="autoNakyma_RowEditing" 
        OnRowUpdating="autoNakyma_RowUpdating" >

    </asp:GridView>
    <asp:Button ID="addNew" runat="server" OnClick="addNew_Click" Text="Lisää uusi" />
</asp:Content>

